name: agnostic_split_view
description: "A framework-agnostic split view for Flutter. Zero Material/Cupertino
  dependencies. Headless, themable, high-performance."
version: 0.1.1

topics:
  - split-view
  - layout
  - responsive
  - flutter
  - widgets

homepage: https://github.com/muhammad-abdal/agnostic_split_view
repository: https://github.com/muhammad-abdal/agnostic_split_view
issue_tracker: https://github.com/muhammad-abdal/agnostic_split_view/issues

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
